/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.stomas.imc.GUI;

import com.stomas.imc.Exceptions.PersonaException;
import com.stomas.imc.Logica.Calculadora;
import com.stomas.imc.Logica.Persona;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author parag
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        txt_altura = new javax.swing.JTextField();
        rb_hombre = new javax.swing.JRadioButton();
        rb_mujer = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ls_personas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        lb_valor_IMC = new javax.swing.JLabel();
        lb_resultado = new javax.swing.JLabel();
        bt_limpiar_formulario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 220, -1));
        jPanel1.add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, -1));

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        jPanel1.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, -1));
        jPanel1.add(txt_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));

        txt_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alturaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 110, -1));

        bg_sexo.add(rb_hombre);
        rb_hombre.setText("Hombre");
        rb_hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_hombreActionPerformed(evt);
            }
        });
        jPanel1.add(rb_hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        bg_sexo.add(rb_mujer);
        rb_mujer.setText("Mujer");
        jPanel1.add(rb_mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("Rut");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("Edad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("Peso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Altura");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setText("Género");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 350, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(ls_personas);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 304, 170));

        jButton1.setText("Calcular IMC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lb_valor_IMC.setText("---");
        jPanel3.add(lb_valor_IMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lb_resultado.setText("---");
        jPanel3.add(lb_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 120, -1));

        bt_limpiar_formulario.setText("Limpiar Formulario");
        bt_limpiar_formulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiar_formularioActionPerformed(evt);
            }
        });
        jPanel3.add(bt_limpiar_formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 350, 280));

        jLabel7.setText("Calculadora IMC");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_hombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_hombreActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            
            
            
            Integer imc;
            p.setNombre(this.txt_nombre.getText());
            p.setRut(this.txt_rut.getText());
            p.setEdad(Integer.valueOf(this.txt_edad.getText()));
            p.setAltura(Double.valueOf(this.txt_altura.getText()));
            p.setPeso(Double.valueOf(this.txt_peso.getText()));
            c.setPersona(p);
            
            if (this.rb_hombre.isSelected()) {
                p.setSexo("H");
            } else if (this.rb_mujer.isSelected()) {
                p.setSexo("M");
            } else{
                throw new Exception("Ninguna opcion marcada en Género");
            }
            imc = c.calcularIMC();
            
            this.lb_valor_IMC.setText(c.getPeso_ideal().toString());
            if (imc == -1) {
                this.lb_resultado.setText("Debajo del peso ideal");
            } else if (imc == 0) {
                this.lb_resultado.setText("Bien de Peso");
            } else if (imc == 1) {
                this.lb_resultado.setText("Sobrepeso");
            }
            
            c.getLista_personas().add("Nombre: "+ p.getNombre()+", edad: "+p.getEdad().toString()+", Género: "+p.getSexo()+", CalculoIMC: "+c.getPeso_ideal().toString()+".");
            loadList();
        } catch (PersonaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_limpiar_formularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiar_formularioActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_bt_limpiar_formularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void loadList() {
        DefaultListModel<String> modelo = new DefaultListModel<String>();
        for (String per :c.getLista_personas()) {
            modelo.addElement(per);
        }
        this.ls_personas.setModel(modelo);
    }
    private void limpiarFormulario(){
        this.txt_nombre.setText("");
        this.txt_rut.setText("");
        this.txt_altura.setText("");
        this.txt_peso.setText("");
        this.txt_edad.setText("");
        this.bg_sexo.clearSelection();
        this.lb_resultado.setText("---");
        this.lb_valor_IMC.setText("---");
        
    }
    

    

    Persona p = new Persona();
    Calculadora c = new Calculadora();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_sexo;
    private javax.swing.JButton bt_limpiar_formulario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_resultado;
    private javax.swing.JLabel lb_valor_IMC;
    private javax.swing.JList<String> ls_personas;
    private javax.swing.JRadioButton rb_hombre;
    private javax.swing.JRadioButton rb_mujer;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
